import Head from 'next/head'
import Navbar from '../components/nav'
import Footer from '../components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <main>
          <Navbar />
          <section className="mid">
            <div>
              <p>Bienvenue sur le Portfolio de <br /><span className="c2fde">Charles de Feligonde</span></p>
            </div>
          </section>
        </main>
        <Footer />
      </div>
    </>
  )
}
